language: csharp
sudo: required
mono: none
dotnet: 2.0.0
dist: trusty

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

services:
  - docker

install:
- git fetch --unshallow

script:
- ./build/travis.sh

after_script:
- ./build.sh -t Coveralls