language: csharp
sudo: required
mono: none
dotnet: 2.0.0
dist: trusty

services:
  - docker

install:
- git fetch origin +refs/heads/*:refs/remotes/origin/*

script:
- ./build/travis.sh

after_script:
- ./build.sh -t Coveralls